#!/usr/bin/env python3
"""Generate app/src/main/res/raw/watchface.xml (Watch Face Format v2) for Sunburst Navy.

The artwork is pre-rendered bitmaps (see render_assets.py); this file only places and
animates them. Hand placement comes from hand_layout.json, written by render_assets.py.
"""

import json
from pathlib import Path

from face import (
    DATE_BORDER, DATE_CX, DATE_CY, DATE_H, DATE_W, PRINT, READOUT_H, READOUT_LEFT_X,
    READOUT_RIGHT_X, READOUT_W, READOUT_Y, SIZE,
)

ROOT = Path(__file__).resolve().parent


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def ambient(target, value):
    return f'<Variant mode="AMBIENT" target="{target}" value="{value}"/>'


def full_image(name, resource, normal_alpha, ambient_alpha):
    return (
        f'<PartImage name="{name}" x="0" y="0" width="{SIZE}" height="{SIZE}" alpha="{normal_alpha}">'
        f'{ambient("alpha", ambient_alpha)}<Image resource="{resource}"/></PartImage>'
    )


def clock(element, resource, lay, ambient_alpha=None, tick=False):
    """One AnalogClock per hand layer so shadows stack correctly between hands."""
    variant = ambient("alpha", ambient_alpha) if ambient_alpha is not None else ""
    motion = '<Tick strength="0.25" duration="0.15"/>' if tick else ""
    return (
        f'<AnalogClock x="0" y="0" width="{SIZE}" height="{SIZE}">{variant}'
        f'<{element} resource="{resource}" x="{f(lay["x"])}" y="{f(lay["y"])}" width="{lay["w"]}" '
        f'height="{lay["h"]}" pivotX="{lay["px"]:.5f}" pivotY="{lay["py"]:.5f}">{motion}</{element}>'
        "</AnalogClock>"
    )


def date_text(name, color, normal_alpha, ambient_alpha):
    aw, ah = DATE_W - 2 * DATE_BORDER, DATE_H - 2 * DATE_BORDER
    return (
        f'<PartText name="{name}" x="{f(DATE_CX - aw / 2)}" y="{f(DATE_CY - ah / 2)}" width="{f(aw)}" '
        f'height="{f(ah)}" alpha="{normal_alpha}">{ambient("alpha", ambient_alpha)}'
        f'<Text align="CENTER"><Font family="SYNC_TO_DEVICE" size="24" weight="MEDIUM" color="{color}">'
        f'<Template>%s<Parameter expression="[DAY]"/></Template></Font></Text></PartText>'
    )


def complication_slot(slot_id, x, provider, display_name):
    """Printed-style readout: monochrome icon + value. Swappable via Customize on the watch."""
    body = (
        f'<PartImage x="4" y="8" width="22" height="22" tintColor="{PRINT}">'
        f'<Image resource="[COMPLICATION.MONOCHROMATIC_IMAGE]"/></PartImage>'
        f'<PartText x="31" y="0" width="{READOUT_W - 31}" height="{READOUT_H}">'
        f'<Text align="START" ellipsis="TRUE">'
        f'<Font family="SYNC_TO_DEVICE" size="22" weight="MEDIUM" color="{PRINT}" letterSpacing="0.04">'
        f'<Template>%s<Parameter expression="[COMPLICATION.TEXT]"/></Template>'
        f"</Font></Text></PartText>"
    )
    complications = "".join(f'<Complication type="{t}">{body}</Complication>' for t in ("SHORT_TEXT", "RANGED_VALUE"))
    return (
        f'<ComplicationSlot slotId="{slot_id}" displayName="{display_name}" x="{f(x)}" y="{f(READOUT_Y)}" '
        f'width="{READOUT_W}" height="{READOUT_H}" supportedTypes="SHORT_TEXT RANGED_VALUE" isCustomizable="TRUE">'
        f'<DefaultProviderPolicy defaultSystemProvider="{provider}" defaultSystemProviderType="SHORT_TEXT"/>'
        f'<BoundingBox x="0" y="0" width="{READOUT_W}" height="{READOUT_H}"/>'
        f"{ambient('alpha', 150)}{complications}</ComplicationSlot>"
    )


def build_xml(layout):
    s = [
        # Active: rendered sunburst dial. Ambient (always-on): black dial with outlined markers.
        full_image("dial", "dial", 255, 0),
        full_image("dial_ambient", "dial_ambient", 0, 255),
        date_text("date", "#FF151A22", 255, 0),
        date_text("date_ambient", PRINT, 0, 200),
        complication_slot(0, READOUT_LEFT_X, "STEP_COUNT", "Left readout"),
        complication_slot(1, READOUT_RIGHT_X, "HEART_RATE", "Right readout"),
        clock("HourHand", "hand_hour_shadow", layout["hour_shadow"], ambient_alpha=0),
        clock("HourHand", "hand_hour", layout["hour"], ambient_alpha=220),
        clock("MinuteHand", "hand_minute_shadow", layout["minute_shadow"], ambient_alpha=0),
        clock("MinuteHand", "hand_minute", layout["minute"], ambient_alpha=220),
        clock("SecondHand", "hand_second_shadow", layout["second_shadow"], ambient_alpha=0, tick=True),
        clock("SecondHand", "hand_second", layout["second"], ambient_alpha=0, tick=True),
    ]
    scene = "\n    ".join(s)
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- GENERATED by watchface/generate.py - edit that file, not this one. -->\n"
        f'<WatchFace width="{SIZE}" height="{SIZE}" clipShape="CIRCLE">\n'
        '  <Metadata key="CLOCK_TYPE" value="ANALOG"/>\n'
        '  <Metadata key="PREVIEW_TIME" value="10:08:36"/>\n'
        '  <Scene backgroundColor="#FF000000">\n'
        f"    {scene}\n"
        "  </Scene>\n"
        "</WatchFace>\n"
    )


def main():
    layout = json.loads((ROOT / "hand_layout.json").read_text())
    out = ROOT / "app/src/main/res/raw/watchface.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_xml(layout))
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
